In [1]:
# Global Renewable Energy Trends -- Data Cleaning
# Author: Lawrence Kipchirchir
# Tool: Python (Jypiter Notebook)
# Source: Our World in Data -- Energy Dataset


#Importing Libraries
import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

In [2]:
#Loading Dataset
url = "https://raw.githubusercontent.com/owid/energy-data/refs/heads/master/owid-energy-data.csv"
df = pd.read_csv(url)
df

,country,year,iso_code,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,biofuel_share_energy,carbon_intensity_elec,coal_cons_change_pct,coal_cons_change_twh,coal_cons_per_capita,coal_consumption,coal_elec_per_capita,coal_electricity,coal_prod_change_pct,coal_prod_change_twh,coal_prod_per_capita,coal_production,coal_share_elec,coal_share_energy,electricity_demand,electricity_demand_per_capita,electricity_generation,electricity_share_energy,energy_cons_change_pct,energy_cons_change_twh,energy_per_capita,energy_per_gdp,fossil_cons_change_pct,fossil_cons_change_twh,fossil_elec_per_capita,fossil_electricity,fossil_energy_per_capita,fossil_fuel_consumption,fossil_share_elec,fossil_share_energy,gas_cons_change_pct,gas_cons_change_twh,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,gas_prod_change_pct,gas_prod_change_twh,gas_prod_per_capita,gas_production,gas_share_elec,gas_share_energy,greenhouse_gas_emissions,hydro_cons_change_pct,hydro_cons_change_twh,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,hydro_share_elec,hydro_share_energy,low_carbon_cons_change_pct,low_carbon_cons_change_twh,low_carbon_consumption,low_carbon_elec_per_capita,low_carbon_electricity,low_carbon_energy_per_capita,low_carbon_share_elec,low_carbon_share_energy,net_elec_imports,net_elec_imports_share_demand,nuclear_cons_change_pct,nuclear_cons_change_twh,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,nuclear_share_elec,nuclear_share_energy,oil_cons_change_pct,oil_cons_change_twh,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,oil_prod_change_pct,oil_prod_change_twh,oil_prod_per_capita,oil_production,oil_share_elec,oil_share_energy,other_renewable_consumption,other_renewable_electricity,other_renewable_exc_biofuel_electricity,other_renewables_cons_change_pct,other_renewables_cons_change_twh,other_renewables_elec_per_capita,other_renewables_elec_per_capita_exc_biofuel,other_renewables_energy_per_capita,other_renewables_share_elec,other_renewables_share_elec_exc_biofuel,other_renewables_share_energy,per_capita_electricity,primary_energy_consumption,renewables_cons_change_pct,renewables_cons_change_twh,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,renewables_share_elec,renewables_share_energy,solar_cons_change_pct,solar_cons_change_twh,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
0,ASEAN (Ember),2000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.87,1.550,NaN,572.52,NaN,NaN,NaN,NaN,NaN,76.03,NaN,NaN,NaN,NaN,20.081,NaN,378.61,NaN,378.61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305.36,NaN,NaN,80.653,NaN,NaN,NaN,NaN,NaN,164.26,NaN,NaN,NaN,NaN,NaN,43.385,NaN,216.76,NaN,NaN,NaN,NaN,50.45,NaN,13.325,NaN,NaN,NaN,NaN,NaN,73.25,NaN,19.347,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,65.07,NaN,NaN,NaN,NaN,NaN,17.187,NaN,NaN,22.80,16.93,NaN,NaN,NaN,NaN,NaN,6.022,4.472,NaN,NaN,NaN,NaN,NaN,NaN,NaN,73.25,NaN,19.347,NaN,NaN,NaN,NaN,NaN,0.00,NaN,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
1,ASEAN (Ember),2001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.46,1.596,NaN,570.24,NaN,NaN,NaN,NaN,NaN,86.26,NaN,NaN,NaN,NaN,21.307,NaN,404.85,NaN,404.85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,327.66,NaN,NaN,80.934,NaN,NaN,NaN,NaN,NaN,190.41,NaN,NaN,NaN,NaN,NaN,47.032,NaN,230.86,NaN,NaN,NaN,NaN,54.33,NaN,13.420,NaN,NaN,NaN,NaN,NaN,77.19,NaN,19.066,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,50.99,NaN,NaN,NaN,NaN,NaN,12.595,NaN,NaN,22.86,16.40,NaN,NaN,NaN,NaN,NaN,5.647,4.051,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.19,NaN,19.066,NaN,NaN,NaN,NaN,NaN,0.00,NaN,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
2,ASEAN (Ember),2002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.62,1.528,NaN,572.68,NaN,NaN,NaN,NaN,NaN,93.43,NaN,NaN,NaN,NaN,21.568,NaN,433.19,NaN,433.19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,356.67,NaN,NaN,82.336,NaN,NaN,NaN,NaN,NaN,208.92,NaN,NaN,NaN,NaN,NaN,48.228,NaN,248.08,NaN,NaN,NaN,NaN,53.29,NaN,12.302,NaN,NaN,NaN,NaN,NaN,76.52,NaN,17.664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,54.32,NaN,NaN,NaN,NaN,NaN,12.540,NaN,NaN,23.23,16.61,NaN,NaN,NaN,NaN,NaN,5.363,3.834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.52,NaN,17.664,NaN,NaN,NaN,NaN,NaN,0.00,NaN,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
3,ASEAN (Ember),2003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.45,1.626,NaN,577.02,NaN,NaN,NaN,NaN,NaN,102.01,NaN,NaN,NaN,NaN,22.258,NaN,458.30,NaN,458.30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,381.90,NaN,NaN,83.330,NaN,NaN,NaN,NaN,NaN,226.51,NaN,NaN,NaN,NaN,NaN,49.424,NaN,264.45,NaN,NaN,NaN,NaN,53.21,NaN,11.610,NaN,NaN,NaN,NaN,NaN,76.40,NaN,16.670,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,53.38,NaN,NaN,NaN,NaN,NaN,11.647,NaN,NaN,23.19,15.74,NaN,NaN,NaN,NaN,NaN,5.060,3.434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,76.40,NaN,16.670,NaN,NaN,NaN,NaN,NaN,0.00,NaN,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
4,ASEAN (Ember),2004,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.40,1.691,NaN,583.61,NaN,NaN,NaN,NaN,NaN,115.01,NaN,NaN,NaN,NaN,23.158,NaN,496.63,NaN,496.63,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,418.67,NaN,NaN,84.302,NaN,NaN,NaN,NaN,NaN,244.16,NaN,NaN,NaN,NaN,NaN,49.163,NaN,289.84,NaN,NaN,NaN,NaN,52.99,NaN,10.670,NaN,NaN,NaN,NaN,NaN,77.96,NaN,15.698,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN,NaN,NaN,NaN,NaN,59.50,NaN,NaN,NaN,NaN,NaN,11.981,NaN,NaN,24.97,16.57,NaN,NaN,NaN,NaN,NaN,5.028,3.336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.96,NaN,15.698,NaN,NaN,NaN,NaN,NaN,0.00,NaN,0.000,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23227,Zimbabwe,2020,ZWE,15526887.0,2.317871e+10,NaN,0.0,0.0,0.0,6.440,0.10,1.490,NaN,371.09,NaN,NaN,NaN,NaN,176.468,2.74,3.004,0.592,1306.886,20.292,40.835,NaN,8.69,559.674,6.71,NaN,-15.539,-6.179,2163.068,1.449,NaN,NaN,179.044,2.78,NaN,NaN,41.431,NaN,NaN,NaN,NaN,0.0,0.00,NaN,NaN,NaN,NaN,NaN,0.000,NaN,2.49,NaN,NaN,NaN,245.381,3.81,NaN,56.781,NaN,NaN,NaN,NaN,253.109,3.93,NaN,58.569,NaN,1.98,22.785,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,2.576,0.04,NaN,NaN,NaN,NaN,NaN,0.596,NaN,NaN,0.10,0.00,NaN,NaN,6.440,0.0,NaN,1.490,0.000,NaN,432.154,33.586,NaN,NaN,NaN,253.109,3.93,NaN,58.569,NaN,NaN,NaN,NaN,1.288,0.02,NaN,0.298,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23228,Zimbabwe,2021,ZWE,15797220.0,2.514009e+10,NaN,0.0,0.0,0.0,6.963,0.11,1.284,NaN,269.55,NaN,NaN,NaN,NaN,158.889,2.51,19.708,3.999,1537.673,24.291,29.288,NaN,10.31,652.646,8.57,NaN,12.059,4.050,2382.434,1.497,NaN,NaN,158.889,2.51,NaN,NaN,29.288,NaN,NaN,NaN,NaN,0.0,0.00,NaN,NaN,NaN,NaN,NaN,0.000,NaN,2.31,NaN,NaN,NaN,375.383,5.93,NaN,69.195,NaN,NaN,NaN,NaN,383.612,6.06,NaN,70.712,NaN,1.74,16.877,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.000,0.00,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN,0.11,0.00,NaN,NaN,6.963,0.0,NaN,1.284,0.000,NaN,542.500,37.636,NaN,NaN,NaN,383.612,6.06,NaN,70.712,NaN,NaN,NaN,NaN,1.266,0.02,NaN,0.233,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23229,Zimbabwe,2022,ZWE,16069061.0,2.590159e+10,NaN,0.0,0.0,0.0,6.845,0.11,1.230,NaN,297.54,NaN,NaN,NaN,NaN,181.716,2.92,21.665,5.263,1839.164,29.554,32.662,NaN,10.85,675.211,8.94,NaN,55.118,20.744,3633.067,2.254,NaN,NaN,181.716,2.92,NaN,NaN,32.662,NaN,NaN,NaN,NaN,0.0,0.00,NaN,NaN,NaN,NaN,NaN,0.000,NaN,2.66,NaN,NaN,NaN,365.921,5.88,NaN,65.772,NaN,NaN,NaN,NaN,374.633,6.02,NaN,67.338,NaN,1.91,17.604,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.000,0.00,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN,0.11,0.00,NaN,NaN,6.845,0.0,NaN,1.230,0.000,NaN,556.349,58.380,NaN,NaN,NaN,374.633,6.02,NaN,67.338,NaN,NaN,NaN,NaN,1.867,0.03,NaN,0.336,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23230,Zimbabwe,2023,ZWE,16340829.0,NaN,NaN,0.0,0.0,0.0,7.344,0.12,1.444,NaN,298.44,NaN,NaN,NaN,NaN,165.230,2.70,26.593,7.859,2289.525,37.413,32.491,NaN,10.21,624.815,8.31,NaN,-10.952,-6.394,3181.361,NaN,NaN,NaN,165.230,2.70,NaN,NaN,32.491,NaN,NaN,NaN,NaN,0.0,0.00,NaN,NaN,NaN,NaN,NaN,0.000,NaN,2.48,NaN,NaN,NaN,334.132,5.46,NaN,65.704,NaN,NaN,NaN,NaN,343.312,5.61,NaN,67.509,NaN,1.90,18.609,NaN,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.000,0.00,NaN,NaN,NaN,NaN,NaN,0.000,NaN,NaN,0.12,0.00,NaN,NaN,7.344,0.0,NaN,1.444,0.000,NaN,508.542,51.986,NaN,NaN,NaN,343.312,5.61,NaN,67.509,NaN,NaN,NaN,NaN,1.836,0.03,NaN,0.361,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,NaN
23231,Zimbabwe,2024,ZWE,16634366.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.205,6.063,2613.587,43.475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
# Exploratory Data Analysis
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23232 entries, 0 to 23231
Columns: 130 entries, country to wind_share_energy
dtypes: float64(127), int64(1), object(2)
memory usage: 23.0+ MB

In [4]:
df.describe()

,year,population,gdp,biofuel_cons_change_pct,biofuel_cons_change_twh,biofuel_cons_per_capita,biofuel_consumption,biofuel_elec_per_capita,biofuel_electricity,biofuel_share_elec,biofuel_share_energy,carbon_intensity_elec,coal_cons_change_pct,coal_cons_change_twh,coal_cons_per_capita,coal_consumption,coal_elec_per_capita,coal_electricity,coal_prod_change_pct,coal_prod_change_twh,coal_prod_per_capita,coal_production,coal_share_elec,coal_share_energy,electricity_demand,electricity_demand_per_capita,electricity_generation,electricity_share_energy,energy_cons_change_pct,energy_cons_change_twh,energy_per_capita,energy_per_gdp,fossil_cons_change_pct,fossil_cons_change_twh,fossil_elec_per_capita,fossil_electricity,fossil_energy_per_capita,fossil_fuel_consumption,fossil_share_elec,fossil_share_energy,gas_cons_change_pct,gas_cons_change_twh,gas_consumption,gas_elec_per_capita,gas_electricity,gas_energy_per_capita,gas_prod_change_pct,gas_prod_change_twh,gas_prod_per_capita,gas_production,gas_share_elec,gas_share_energy,greenhouse_gas_emissions,hydro_cons_change_pct,hydro_cons_change_twh,hydro_consumption,hydro_elec_per_capita,hydro_electricity,hydro_energy_per_capita,hydro_share_elec,hydro_share_energy,low_carbon_cons_change_pct,low_carbon_cons_change_twh,low_carbon_consumption,low_carbon_elec_per_capita,low_carbon_electricity,low_carbon_energy_per_capita,low_carbon_share_elec,low_carbon_share_energy,net_elec_imports,net_elec_imports_share_demand,nuclear_cons_change_pct,nuclear_cons_change_twh,nuclear_consumption,nuclear_elec_per_capita,nuclear_electricity,nuclear_energy_per_capita,nuclear_share_elec,nuclear_share_energy,oil_cons_change_pct,oil_cons_change_twh,oil_consumption,oil_elec_per_capita,oil_electricity,oil_energy_per_capita,oil_prod_change_pct,oil_prod_change_twh,oil_prod_per_capita,oil_production,oil_share_elec,oil_share_energy,other_renewable_consumption,other_renewable_electricity,other_renewable_exc_biofuel_electricity,other_renewables_cons_change_pct,other_renewables_cons_change_twh,other_renewables_elec_per_capita,other_renewables_elec_per_capita_exc_biofuel,other_renewables_energy_per_capita,other_renewables_share_elec,other_renewables_share_elec_exc_biofuel,other_renewables_share_energy,per_capita_electricity,primary_energy_consumption,renewables_cons_change_pct,renewables_cons_change_twh,renewables_consumption,renewables_elec_per_capita,renewables_electricity,renewables_energy_per_capita,renewables_share_elec,renewables_share_energy,solar_cons_change_pct,solar_cons_change_twh,solar_consumption,solar_elec_per_capita,solar_electricity,solar_energy_per_capita,solar_share_elec,solar_share_energy,wind_cons_change_pct,wind_cons_change_twh,wind_consumption,wind_elec_per_capita,wind_electricity,wind_energy_per_capita,wind_share_elec,wind_share_energy
count,23232.000000,1.876000e+04,1.178000e+04,2070.000000,7903.000000,6338.000000,8057.000000,5796.000000,6107.000000,6082.000000,6379.000000,6106.000000,5827.000000,6293.000000,5145.000000,6405.000000,6298.000000,6969.000000,9922.000000,16562.000000,14808.000000,16822.000000,6944.000000,6379.000000,6149.000000,5838.000000,7684.000000,4081.000000,12745.000000,12978.000000,11086.000000,7882.000000,6267.000000,6293.000000,6310.000000,6981.000000,5145.000000,6405.000000,6956.000000,6379.000000,5643.000000,6293.000000,6405.000000,6182.000000,6853.000000,5145.000000,8.103000e+03,16990.000000,15028.000000,17251.000000,6830.000000,6379.000000,5762.000000,5686.000000,6293.000000,6405.000000,8286.000000,9377.000000,5145.000000,7552.000000,6379.000000,5902.000000,6293.000000,6405.000000,8380.000000,9471.000000,5145.000000,7646.000000,6379.000000,5839.000000,5816.000000,2579.000000,7717.000000,7859.000000,8972.000000,10063.000000,6585.000000,7555.000000,6379.000000,6267.000000,6293.000000,6405.000000,6249.000000,6920.000000,5145.000000,10182.000000,17729.000000,1.557400e+04,17992.000000,6895.000000,6379.000000,6405.000000,9440.000000,5532.000000,3988.000000,6293.000000,8349.000000,5221.000000,5145.000000,7615.000000,5507.000000,6379.000000,6853.000000,13255.000000,5895.000000,6293.000000,6405.000000,8380.000000,9471.000000,5145.000000,7646.000000,6379.000000,2515.000000,6293.000000,6405.000000,8394.000000,9485.000000,5145.000000,7640.000000,6379.000000,2798.000000,6293.000000,6405.000000,8237.000000,9328.000000,5145.000000,7483.000000,6379.000000
mean,1975.937543,1.057591e+08,4.257565e+11,43.478804,1.054261,55.157112,15.092054,71.064594,12.190516,1.962603,0.227463,478.178851,22.886058,27.702004,5805.012363,1682.740230,706.174542,329.046022,18.372174,17.013823,3468.441007,988.387708,17.270928,18.215400,637.755758,4063.936855,800.696827,16.108716,4.237759,83.495941,25908.742204,1.686102,3.278364,96.807090,2464.346660,550.979269,31749.398190,5271.007780,65.062220,86.070841,18.526292,33.585067,1284.206380,914.960007,183.180976,9977.031536,1.150588e+14,17.562447,6655.441978,625.121302,19.655019,20.096153,339.126621,5.826474,7.817135,379.975274,983.780658,121.459649,3449.314977,25.102898,9.337810,11.394551,29.272078,793.534450,1507.764360,258.754948,5723.046909,35.529593,13.929158,0.112949,1.086694,32.428606,5.482233,228.029940,313.581786,90.840326,1123.540979,5.814833,2.811101,3.079877,35.520018,2304.061160,891.329757,45.198318,15967.354321,21.800835,23.929228,2.597500e+04,1230.348421,29.034253,47.759285,42.552749,13.212453,2.079872,32.761337,2.369019,103.615329,70.082564,470.588292,2.412104,0.759103,0.814829,4054.599502,4254.768667,11.091356,22.549306,513.739404,1172.040479,162.252049,4285.045479,29.786532,11.118054,124.399043,5.017571,23.625814,28.961382,9.275418,82.236808,0.970060,0.219802,290.408294,6.021235,48.691257,68.159540,19.811565,214.958712,1.655011,0.518141
std,35.234386,4.697550e+08,3.507870e+12,286.672317,6.641947,180.660550,75.942529,202.044885,51.641144,5.356652,0.662848,241.595818,762.940352,222.550671,8403.061176,5153.876458,1345.376504,1155.069690,615.977898,198.647187,9727.472361,3586.851616,24.120737,19.035018,2531.199169,5086.413168,2654.091396,7.084413,46.829466,497.365883,38288.643872,1.637284,22.531171,498.967728,3159.820915,1797.091661,33139.280553,14359.423359,31.082437,14.523628,308.302489,148.805514,3670.941632,2300.516273,587.397849,21604.975865,1.035721e+16,110.810221,37523.188248,2484.993625,26.443933,18.935074,1373.817761,38.273605,46.671638,1033.366729,3195.864210,377.507208,10375.113112,29.256896,12.138771,112.517534,116.692881,2374.575375,3961.129627,874.825669,13271.244222,31.485147,14.523628,9.003634,41.483976,328.384623,43.785321,852.477995,961.634752,342.292969,2928.630179,13.080006,5.979653,22.063270,233.888770,6079.290687,1922.396737,141.441932,16898.625918,441.906420,213.130043,1.640531e+05,4243.655989,36.263011,20.054104,159.859833,52.851005,7.530434,516.287115,10.578808,726.509595,889.317763,2963.942658,6.101191,3.712513,2.173076,5042.679722,14897.508937,113.451949,101.024860,1572.129560,3694.592902,566.958066,12497.248070,30.545183,13.269041,704.897749,38.692250,179.415252,114.223545,72.243813,302.862174,2.961911,0.766125,6070.498582,34.260028,281.755752,275.338849,117.845094,733.879417,4.909754,1.722172
min,1900.000000,1.776000e+03,1.642060e+08,-100.000000,-59.084000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-100.000000,-1988.192000,0.000000,0.000000,0.000000,0.000000,-100.000000,-2376.152000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.040000,-100.000000,-12613.266000,0.000000,0.000000,-49.591000,-9069.922000,0.000000,0.000000,0.000000,0.000000,0.000000,13.874000,-95.245000,-3749.125000,0.000000,0.000000,0.000000,0.000000,-1.000000e+02,-4092.556000,0.000000,0.000000,0.000000,0.000000,0.000000,-81.250000,-441.637000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-88.208000,-669.799000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-93.320000,-772.594000,-100.000000,-534.551000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-73.921000,-4896.020000,0.000000,0.000000,0.000000,0.000000,-100.000000,-6455.246000,0.000000e+00,0.000000,0.000000,8.058000,0.000000,0.000000,0.000000,-100.000000,-48.202000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-92.641000,-430.247000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-100.000000,-4.592000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-100.000000,-46.535000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1949.000000,1.600333e+06,1.426394e+10,-0.968000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,297.015000,-4.980000,-1.297000,304.310000,4.349000,0.000000,0.000000,-4.082250,0.000000,0.000000,0.000000,0.000000,2.001000,1.560000,664.571000,2.412500,12.259000,-0.525000,-0.052000,2833.457000,0.769000,-0.668500,-1.397000,254.307750,0.640000,10360.155000,142.380000,42.831750,80.819000,-0.557000,0.000000,11.881000,0.000000,0.000000,613.122000,-8.640000e-01,0.000000,0.000000,0.000000,0.000000,4.941500,0.300000,-3.890250,-0.519000,3.517000,6.971250,0.100000,121.071000,0.616750,1.104500,-0.604250,-0.028000,7.050000,30.305250,0.250000,259.640000,5.663250,3.336000,0.000000,0.000000,-1.425000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.194500,-1.666000,80.389000,26.774000,0.150000,5097.861000,-3.091750,0.000000,0.000000e+00,0.000000,2.032500,33.958000,0.000000,0.000000,0.000000,-0.270750,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,659.878000,8.002500,-1.338000,-0.061000,5.299000,28.209750,0.223000,208.402000,3.513750,2.127000,10.564000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.329000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1985.000000,6.950666e+06,4.357680e+10,6.695500,0.000000,0.000000,0.000000,0.874000,0.020000,0.153500,0.000000,525.260000,1.269000,0.023000,2581.504000,47.364000,0.000000,0.340000,2.222500,0.000000,30.580000,1.625500,1.835000,12.559000,12.530000,2610.463000,22.545000,15.457000,2.483000,0.802000,12666.641500,1.250500,2.623000,7.005000,1418.779500,10.090000,24974.670000,406.549000,70.950500,90.365000,4.083000,1.872000,82.809000,89.808000,2.510000,4265.978000,4.167000e+00,0.000000,0.000000,0.000000,9.849500,16.468000,3.365000,2.818500,0.128000,28.391000,140.595500,3.720000,627.570000,13.678000,5.361000,4.364000,1.014000,51.767000,261.864500,6.270000,1480.613000,29.614500,9.635000,0.000000,0.000000,3.320000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.386000,3.615000,204.001000,157.294000,1.280000,11817.343000,1.756000,0.000000,5.566500e+00,1.896000,8.633000,43.903000,0.555000,0.030000,0.000000,5.055000,0.000000,0.226000,0.000000,19.933000,0.258000,0.000000,0.118000,2587.653000,91.187000,4.529000,0.701000,37.118000,216.598000,4.610000,914.872000,18.500000,6.551000,28.408000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.349500,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2005.000000,2.575218e+07,1.830576e+11,23.320750,0.000000,0.506750,0.062000,44.114250,0.920000,1.608250,0.049500,650.270000,7.309500,6.111000,8447.372000,446.305000,817.645250,36.060000,9.101500,0.887000,2090.021000,122.957500,32.038500,29.608000,94.360000,5779.924000,158.810500,18.591000,6.301000,16.594000,36635.574250,2.065750,5.971000,41.473000,3533.735250,127.570000,40051.789000,1870.448000,94.286000,96.664000,9.988500,16.274000,440.570000,853.342000,46.400000,10490.071000,1.099150e+01,1.348250,770.654500,62.224500,27.523000,28.062500,41.045000,10.733750,4.757000,157.449000,710.102500,30.860000,2269.737000,41.914750,11.988500,11.180750,10.937000,263.190000,1415.445750,49.490000,5511.771000,59.340250,19.181000,0.525000,2.236500,14.155000,0.000000,25.768000,0.000000,3.977000,150.660000,2.248000,2.137000,6.423000,20.542000,1013.222000,573.542000,12.775000,21160.748000,10.198000,1.756000,2.450072e+03,185.721750,50.010000,60.314500,11.225000,1.650000,0.000000,13.760750,0.441000,39.173000,0.000000,224.509000,1.850000,0.000000,0.706000,5773.835000,772.244500,12.001000,7.878000,190.562000,922.200500,36.723500,3235.735000,50.000000,15.007500,64.152000,0.014000,0.094000,0.607000,0.024000,2.442000,0.214750,0.006000,45.210750,0.096000,0.916000,1.855000,0.120000,25.914000,0.565000,0.074500
max,2025.000000,8.161973e+09,1.301126e+14,6373.062000,144.290000,2587.708000,1366.878000,2450.791000,704.810000,77.586000,7.582000,1306.720000,55400.000000,2811.242000,96194.445000,45850.543000,9421.678000,10543.840000,44965.750000,3189.062000,162212.781000,50618.328000,100.000000,89.157000,30938.180000,56048.727000,30938.180000,68.996000,4462.329000,10790.422000,651836.562000,25.253000,1553.105000,9430.391000,23215.473000,18313.961000,318559.688000,142420.891000,100.000000,100.000000,15299.998000,3625.422000,41278.270000,23215.473000,6900.360000,288358.531000,9.323217e+17,4146.363000,852312.125000,41244.516000,100.000000,91.942000,14597.910000,1750.000000,485.917000,10860.753000,40911.043000,4419.950000,105413.984000,100.000000,71.417000,7518.204000,2359.283000,32850.859000,56048.727000,12624.220000,153153.984000,100.000000,86.126000,66.670000,98.690000,11200.001000,875.458000,7494.948000,8908.020000,2778.760000,24744.818000,88.011000,41.661000,1553.105000,2993.727000,55292.082000,14645.941000,1366.094000,156814.859000,26472.602000,5856.434000,3.443292e+06,52831.051000,100.000000,100.000000,2476.357000,791.790000,87.910000,21131.334000,165.264000,17032.252000,17032.252000,53224.312000,77.586000,48.450000,31.244000,56048.727000,176737.094000,7518.204000,2164.578000,25979.023000,56048.727000,9845.460000,153153.984000,100.000000,86.126000,21800.000000,1123.988000,5150.569000,1879.595000,2128.370000,4584.596000,50.000000,9.881000,242384.859000,642.617000,6124.465000,3947.840000,2505.350000,9315.287000,58.357000,26.085000

In [5]:
df.isna().sum()

country                       0
year                          0
iso_code                   6098
population                 4472
gdp                       11452
                          ...
wind_elec_per_capita      14995
wind_electricity          13904
wind_energy_per_capita    18087
wind_share_elec           15749
wind_share_energy         16853
Length: 130, dtype: int64

In [6]:
# Selecting Relevant Columns
renewable_cols = [
    "country", "year", "iso_code", "population", "gdp",
    "renewables_electricity", "renewables_share_elec",
    "renewables_consumption", "renewables_share_energy",
    "solar_electricity", "solar_share_elec",
    "wind_electricity", "wind_share_elec",
    "hydro_electricity", "hydro_share_elec"
]

df_renew = df[renewable_cols]

In [7]:
# Cleaning the Data
# Dropping rows where renewable electricity is missing
df_renew = df_renew.dropna(subset=["renewables_electricity"], how="all")

# Keeping only country-level rows (removing regional aggregates)
df_renew = df_renew[df_renew["iso_code"].notna()]

# Filtering to modern era (2000 onwards)
df_renew = df_renew[df_renew["year"] >= 2000]

In [8]:
# Validating Cleaned Data
df_renew.isna().sum()

country                       0
year                          0
iso_code                      0
population                    0
gdp                        1397
renewables_electricity        0
renewables_share_elec        25
renewables_consumption     3223
renewables_share_energy    3223
solar_electricity            21
solar_share_elec             46
wind_electricity            158
wind_share_elec             183
hydro_electricity            94
hydro_share_elec            119
dtype: int64

In [9]:
df_renew.describe()

,year,population,gdp,renewables_electricity,renewables_share_elec,renewables_consumption,renewables_share_energy,solar_electricity,solar_share_elec,wind_electricity,wind_share_elec,hydro_electricity,hydro_share_elec
count,5187.000000,5.187000e+03,3.790000e+03,5187.000000,5162.000000,1964.000000,1964.000000,5166.000000,5141.000000,5029.000000,5004.000000,5093.000000,5068.000000
mean,2011.734914,3.441651e+07,5.697030e+11,25.346805,31.201303,170.056003,12.086738,1.995372,1.213165,4.061094,1.957559,17.483676,25.773871
std,7.067229,1.339810e+08,1.921936e+12,124.508753,32.690939,518.237588,14.608366,19.526241,3.445728,32.121295,5.719988,77.754540,31.305841
min,2000.000000,1.776000e+03,3.128536e+08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2006.000000,9.790265e+05,2.366483e+10,0.030000,1.774000,6.756500,2.014000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2012.000000,6.328042e+06,7.727651e+10,1.290000,18.550000,35.026500,6.654000,0.000000,0.000000,0.000000,0.000000,0.750000,10.252000
75%,2018.000000,2.276159e+07,3.515815e+11,10.145000,55.287250,109.649250,17.672250,0.047500,0.440000,0.140000,0.654250,7.230000,46.780750
max,2025.000000,1.450936e+09,2.696602e+13,3398.830000,100.000000,8470.082000,86.126000,839.040000,50.000000,997.040000,58.357000,1354.250000,100.000000

In [10]:
df_renew.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5187 entries, 125 to 23230
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   country                  5187 non-null   object
 1   year                     5187 non-null   int64
 2   iso_code                 5187 non-null   object
 3   population               5187 non-null   float64
 4   gdp                      3790 non-null   float64
 5   renewables_electricity   5187 non-null   float64
 6   renewables_share_elec    5162 non-null   float64
 7   renewables_consumption   1964 non-null   float64
 8   renewables_share_energy  1964 non-null   float64
 9   solar_electricity        5166 non-null   float64
 10  solar_share_elec         5141 non-null   float64
 11  wind_electricity         5029 non-null   float64
 12  wind_share_elec          5004 non-null   float64
 13  hydro_electricity        5093 non-null   float64
 14  hydro_share_elec         5068 non-null   float64
dtypes: float64(12), int64(1), object(2)
memory usage: 648.4+ KB

In [11]:
#Exporting Cleaned Dataset
df_renew.to_csv('owid-energy-data-cleaned 2000-2022.csv', index=False)